//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 12:34:46 PM CET 
//


package org.bimserver.bcf.markup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.tue.ddss.bcf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.tue.ddss.bcf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Markup }
     * 
     */
    public Markup createMarkup() {
        return new Markup();
    }

    /**
     * Create an instance of {@link nl.tue.ddss.bcf.Topic }
     * 
     */
    public Topic createTopic() { 	//nl.tue.ddss.bcf_markup.
        return new Topic(); 		//nl.tue.ddss.bcf_markup.
    }

    /**
     * Create an instance of {@link Comment.Topic }
     * 
     */
    public Comment.Topic createCommentTopic() {
        return new Comment.Topic();
    }

    /**
     * Create an instance of {@link Header.File }
     * 
     */
    public Header.File createHeaderFile() {
        return new Header.File();
    }

}
