//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 09:34:34 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://buildingsmart-tech.org/mvdXML/mvdXML1-0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.buildingsmart_tech.mvdxml.mvdxml1_0;
