//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.13 at 04:20:51 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://buildingsmart-tech.org/mvdXML/mvdXML1-1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.buildingsmart_tech.mvdxml.mvdxml1_1;
