//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.13 at 04:20:51 PM CET 
//


package org.buildingsmart_tech.mvdxml.mvdxml1_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rules complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rules">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://buildingsmart-tech.org/mvdXML/mvdXML1-1}AbstractRule" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rules", propOrder = {
    "abstractRule"
})
public class Rules {

    @XmlElementRef(name = "AbstractRule", namespace = "http://buildingsmart-tech.org/mvdXML/mvdXML1-1", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractRule>> abstractRule;

    /**
     * 
     * 						Abstract rule that can either be an attribute rule or an entity rule.
     * 					Gets the value of the abstractRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstractRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link EntityRule }{@code >}
     * {@link JAXBElement }{@code <}{@link TemplateRule }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeRule }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractRule }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AbstractRule>> getAbstractRule() {
        if (abstractRule == null) {
            abstractRule = new ArrayList<JAXBElement<? extends AbstractRule>>();
        }
        return this.abstractRule;
    }

}
